import { createGlobalTheme } from '@vanilla-extract/css';

export const theme = createGlobalTheme(':root', {
  color: {
    palette: {
      black: '',
      white: '',
      gray50: '',
      gray100: '',
      gray200: '',
      gray300: '',
      gray400: '',
      gray500: '',
      gray600: '',
      gray700: '',
      gray800: '',
      gray900: '',
      red50: '',
      red100: '',
      red200: '',
      red300: '',
      red400: '',
      red500: '',
      red600: '',
      red700: '',
      red800: '',
      red900: '',
      green50: '',
      green100: '',
      green200: '',
      green300: '',
      green400: '',
      green500: '',
      green600: '',
      green700: '',
      green800: '',
      green900: '',
      blue50: '',
      blue100: '',
      blue200: '',
      blue300: '',
      blue400: '',
      blue500: '',
      blue600: '',
      blue700: '',
      blue800: '',
      blue900: '',
    },
    token: {
      semantic: {
        text: '',
        textMuted: '',
        background: '',
        backgroundInset: '',
        border: '',
        borderMuted: '',
        overlay: '',
        shadow: '',
      },
      button: {
        normal: {
          text: '',
          border: '',
          background: '',
          hover: {
            text: '',
            border: '',
            background: '',
          },
          disabled: {
            text: '',
            border: '',
            background: '',
          },
        },
        primary: {
          text: '',
          border: '',
          background: '',
          hover: {
            text: '',
            border: '',
            background: '',
          },
          disabled: {
            text: '',
            border: '',
            background: '',
          },
        },
        danger: {
          text: '',
          border: '',
          background: '',
          hover: {
            text: '',
            border: '',
            background: '',
          },
          disabled: {
            text: '',
            border: '',
            background: '',
          },
        },
        ghost: {
          text: '',
          border: '',
          background: '',
          hover: {
            text: '',
            border: '',
            background: '',
          },
          disabled: {
            text: '',
            border: '',
            background: '',
          },
        },
      },
      tooltip: {
        text: '',
        background: '',
      },
      toast: {
        normal: {
          title: '',
          description: '',
          border: '',
          background: '',
        },
        success: {
          title: '',
          description: '',
          border: '',
          background: '',
        },
        error: {
          title: '',
          description: '',
          border: '',
          background: '',
        },
      },
      popover: {
        text: '',
        border: '',
        background: '',
      },
    },
  },
  font: {
    size: {
      tiny: '.75rem',
      normal: '.875rem',
      medium: '1rem',
      large: '1.25rem',
    },
    weight: {
      light: '300',
      normal: '400',
      medium: '500',
      semiBold: '600',
    },
  },
  radius: {
    tiny: '2px',
    normal: '4px',
    medium: '6px',
    large: '8px',
    pill: '9999px',
  },
  duration: {
    fast: '100ms',
    normal: '250ms',
    slow: '500ms',
  },
});
