[package]
name = "overlay"
version = "1.0.0"
edition = "2021"

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1

[lib]
crate-type = ["cdylib"]

[dependencies]
ab_glyph = { version = "0.2.32" }
image = { version = "0.25.8" }
imageproc = { version = "0.27.0" }
wasm-bindgen = { version="0.2.104" }
worker = { version="0.8.0" }
