name: Publish

on:
  push:

jobs:
  publish-cdn:
    name: Publish to CDN
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build --filter="@looks-to-me/app-cdn"

      - name: Publish
        working-directory: apps/cdn
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm run deploy --env="${{ github.ref == 'refs/heads/main' && '' || 'next' }}"

  publish-overlay:
    name: Publish to Overlay
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build --filter="@looks-to-me/app-overlay"

      - name: Publish
        working-directory: apps/overlay
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm run deploy --env="${{ github.ref == 'refs/heads/main' && '' || 'next' }}"

  publish-web:
    name: Publish to Web
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      deployments: write
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'looks-to-me (Production)' || 'looks-to-me (Preview)' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build:app --filter="@looks-to-me/app-web"

      - name: Publish
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm run deploy --env="${{ github.ref == 'refs/heads/main' && '' || 'next' }}"
